version: "3"
services:
  app:
    build: ./app
    ports:
      - 10010:80
    environment:
      - FLAG=SEE{x55_15_my_m1ddl3_n4m3_00d21e74f830352781874d57dff7e384}

  admin:
    build: ./admin
    privileged: true
    ports:
      - 10011:8000